name: ğŸ’¡ ILabs
root: ~/repos/techlounge/innovation-labs-website/packages/frontend

windows:
  - ğŸ“ Editor:
      layout: tiled
      panes:
        - nvim
  - ğŸšš Server:
      panes:
        - npm run start
